version: "3.8"
services:
  motiro-frontend:
    extends:
      file: ./docker-compose.yml
      service: motiro-frontend
    volumes:
      - ./app:/app:cached

networks: 
  motiro-nw:
    name: "motiro-nw"