version: "3.8"
services:
  motiro-frontend:
    build: .
    image: motiro-frontend
    container_name: motiro-frontend
    ports:
      - "3000:3000"
    networks:
      - motiro-nw

networks: 
  motiro-nw:
    name: "motiro-nw"